---
name: CloudCMD
version: dev
slug: cloudcmd
description: Recorded media, live TV, online news, and podcasts ready to stream.
url: https://github.com/barisozdag/addon-cloudcmd
webui: http://[HOST]:[PORT:8000]/web
startup: services
init: false
arch:
- aarch64
- amd64
- armv7
- i386
map:
- media:rw
- share:rw
- ssl
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Web interface
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
